sudo: required
language: node_js
node_js:
  - lts/* # stable
install:
  - yarn install # npm ci cache: npm
script:
  - bash ./deploy.sh # yarn build npm run docs:build
branches:
  only:
    - master
# notifications:
#   email: true
